backend:
  name: github
  repo: taluswood/lorros

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Created On, widget: date }
      - { name: body, label: post, widget: markdown }
  - name: getting started
    label: Getting Started
    folder: src/posts/GettingStarted
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Created On, widget: date }
      - { name: body, label: post, widget: markdown }
  - name: discussion
    label: Discussions
    folder: src/posts/Discussions
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Created On, widget: date }
      - { name: body, label: post, widget: markdown }
  - name: groups
    label: Groups
    folder: src/posts/Groups
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Created On, widget: date }
      - { name: body, label: post, widget: markdown }
  - name: meetings
    label: Meetings
    folder: src/posts/Meetings
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Created On, widget: date }
      - { name: body, label: post, widget: markdown }